defaults:
  airports: ["EDDB"]
  start: "2024-01-01T00:00"
  end: "2024-12-31T23:59"
  radius_km: 300
  output_dir: "../assets/datasets"
  task: "all"
  step: "all"

flights:
  check_runway_alignment: true
weather:
  dataset_name: "era5"
  variables: ["temperature", "u_component_of_wind", "v_component_of_wind"]
  pressure_levels: [975, 875, 750, 600, 400, 200]